package com.luyunfeng.outsource.slotwin.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.luyunfeng.outsource.slotwin.bean.Prefecture;
import com.luyunfeng.outsource.slotwin.bean.shop.Shop;

import com.luyunfeng.outsource.slotwin.bean.greendao.PrefectureDao;
import com.luyunfeng.outsource.slotwin.bean.greendao.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig prefectureDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final PrefectureDao prefectureDao;
    private final ShopDao shopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        prefectureDaoConfig = daoConfigMap.get(PrefectureDao.class).clone();
        prefectureDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        prefectureDao = new PrefectureDao(prefectureDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(Prefecture.class, prefectureDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        prefectureDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
    }

    public PrefectureDao getPrefectureDao() {
        return prefectureDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
